version: 2.1
jobs:
   test:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: compile File
          command: gcc test.c -o executable
          #command: |
            #ls
