version: 2.1
jobs:
   test:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: gcc test.c -o executable  
      - run: time ./executable
 workflows:
   jobs:
     - test
